# Generated by Django 3.1.6 on 2023-08-26 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preconstruction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preconstruction',
            name='latitute',
        ),
        migrations.RemoveField(
            model_name='preconstruction',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='preconstruction',
            name='postalcode',
        ),
    ]
