# Generated by Django 3.1.6 on 2023-09-27 05:44

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('preconstruction', '0002_event_event_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preconstruction',
            old_name='builder_sales_email',
            new_name='no_of_units',
        ),
        migrations.RenameField(
            model_name='preconstruction',
            old_name='builder_sales_phone',
            new_name='occupancy',
        ),
        migrations.AddField(
            model_name='city',
            name='details',
            field=django_summernote.fields.SummernoteTextField(blank=True),
        ),
    ]
