# Generated by Django 3.1.6 on 2024-04-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preconstruction', '0005_auto_20240411_0750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=500)),
                ('contact_email', models.CharField(max_length=500, unique=True)),
            ],
        ),
    ]
