# Generated by Django 3.1.6 on 2024-06-04 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preconstruction', '0007_auto_20240415_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='preconstruction',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='leadscount',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preconstruction.partner'),
        ),
    ]
