# Generated by Django 3.1.6 on 2024-08-15 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preconstruction', '0009_news_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preconstruction',
            options={'ordering': ('is_featured', '-last_updated')},
        ),
    ]
