# Generated by Django 3.1.6 on 2024-08-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preconstruction', '0011_auto_20240815_0610'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=100)),
                ('hit_type', models.CharField(max_length=50)),
                ('event_category', models.CharField(blank=True, max_length=100, null=True)),
                ('event_data', models.JSONField(blank=True, null=True)),
                ('page_url', models.URLField()),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
