# Generated by Django 3.1.6 on 2024-08-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preconstruction', '0012_trackingevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingevent',
            name='site_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='trackingevent',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
