# Generated by Django 3.1.6 on 2024-09-12 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preconstruction', '0013_auto_20240820_1845'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrackingEvent',
        ),
    ]
