# Generated by Django 3.1.6 on 2024-10-01 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preconstruction', '0015_city_condos_details_city_detached_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='semi_detached_details',
        ),
    ]
