# Generated by Django 3.1.6 on 2024-11-05 11:11

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('preconstruction', '0017_city_upcoming_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='condos_details',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='detached_details',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='details',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='townhomes_details',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='upcoming_details',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_description',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_description',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='preconstruction',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
