# Generated by Django 3.1.6 on 2026-03-31 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preconstruction', '0018_auto_20241105_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preconstruction',
            name='occupancy',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='preconstruction',
            name='price_starting_from',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='preconstruction',
            name='project_type',
            field=models.CharField(choices=[('Condo', 'Condo'), ('Townhome', 'Townhome'), ('Semi-Detached', 'Semi-Detached'), ('Detached', 'Detached'), ('NaN', 'NaN')], db_index=True, default='NaN', max_length=500),
        ),
        migrations.AlterField(
            model_name='preconstruction',
            name='status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('Selling', 'Selling'), ('Planning Phase', 'Planning Phase'), ('Sold out', 'Sold out')], db_index=True, default='Upcoming', max_length=500),
        ),
        migrations.AddIndex(
            model_name='preconstruction',
            index=models.Index(fields=['-is_featured', '-last_updated'], name='preconstruc_is_feat_8e2ee2_idx'),
        ),
        migrations.AddIndex(
            model_name='preconstruction',
            index=models.Index(fields=['city'], name='preconstruc_city_id_02a650_idx'),
        ),
        migrations.AddIndex(
            model_name='preconstruction',
            index=models.Index(fields=['developer'], name='preconstruc_develop_1b8956_idx'),
        ),
    ]
