# Generated by Django 3.1.6 on 2024-09-12 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('widget_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='id',
            new_name='idd',
        ),
    ]
