# Generated by Django 3.1.6 on 2024-09-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget_tracker', '0002_auto_20240912_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='idd',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
